apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:8.0.29
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: rootPassword
    - name: MYSQL_DATABASE
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: database
    - name: MYSQL_USER
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: user
    - name: MYSQL_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: password
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
