apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.23.0
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx/
    - name: nginx-conf
      mountPath: /etc/nginx/
  - name: fluentd
    image: fluentd:latest
    volumeMounts:
    - name: log-volume
      mountPath: /logs
    - name: fluentd-conf
      mountPath: /fluentd/etc/
  volumes:
  - name: log-volume
    emptyDir: {}
  - name: nginx-conf
    configMap: 
      name: nginx-conf
  - name: fluentd-conf
    configMap: 
      name: fluentd-conf