apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: wordpress-pod
spec:
  containers:
  - name: wordpress
    image: wordpress:6.0.0-apache
    env:
    - name: WORDPRESS_DB_HOST
      valueFrom: 
        configMapKeyRef:
          name: mysql-configmap
          key: db_host
    - name: WORDPRESS_DB_NAME
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: database
    - name: WORDPRESS_DB_USER
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: user
    - name: WORDPRESS_DB_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: mysql-secret
          key: password
