apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: wordpress-pod
spec:
  containers:
    - name: wordpress
      image: wordpress:6.0.0-apache
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wordpress-configmap
              key: db_host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_database
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
data:
  db_host: mysql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
